server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: "secret" # Use the same export password you set
    key-store-type: PKCS12
  http2:
    enabled: true
